name: Test Package on PR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  run-tests:
    uses: Ulthran/pycov3/.github/workflows/pr.yml@main
    secrets:
      CCT: ${{ secrets.CODECOV_TOKEN }}
      GHT: ${{ secrets.GITHUB_TOKEN }}