name: Test Package

on:
  workflow_call:

  workflow_dispatch:

jobs:
  tests_with_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install project
        run: pip install -e .[test]
      - name: Run tests
        run: pytest -s -vvvv -l --tb=long tests
      - name: Generate coverage report
        run: |
          pytest --cov .
          cp .coverage ../
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9, 3.10, 3.11, 3.12]
        os: [ubuntu-latest, macos-latest, windows_latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install project
        run: python -m pip install -e .[test]
      - name: Run tests
        run: pytest -s -vvvv -l --tb=long tests

  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint Code Base
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          VALIDATE_PYTHON_BLACK: true